services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "9022:3100"
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "9021:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      #      - GF_INSTALL_PLUGINS=grafana-loki
      - GF_SERVER_ROOT_URL=http://localhost:9020
      # Remove subpath settings
      - GF_LOG_LEVEL=debug

  websocket:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    container_name: websocket
    ports:
      - "9023:8765"
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=8765
    depends_on:
      - loki

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9020:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - loki
      - grafana
      - websocket

volumes:
  loki_data:
  grafana_data:
